# -*- coding: utf-8 -*-
"""Homicidios años.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/echeverri58/2825b24fbf24eb4b0b82615e1fedecc7/homicidios-a-os.ipynb
"""

h2022 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios.xls'
h2021 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_1.xls'
h2020 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2020_0.xls'
h2019 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2019_3.xlsx'
h2018 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2018_1.xlsx'
h2017 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2017_2.xlsx'
h2016 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2016_2.xlsx'
h2015 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2015_2.xlsx'
h2014 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2014_2.xlsx'
h2013 = 'https://www.policia.gov.co/sites/default/files/delitos-impacto/homicidios_2013_2.xlsx'

h2013_2022 = [h2022, h2021, h2020, h2019, h2018, h2017, h2016, h2015, h2014, h2013]